function data()
return {
	en = {

		["mod_name"] = "German carrying trolley for pa container (medium container)",
		["mod_desc"] = "The use of large containers by rail really took off after 1945. Special carrying wagons were developed for this purpose, which were intended to enable quick and easy reloading. This system became established in the Federal Republic of Germany and was known under the catchy brand name \"Von Haus zu Haus\". Container traffic reached its peak in the sixties with about 25,000 units and about 5,700 large container carrying wagons for their transport. Some of them were on the road in a specially established city express service. From 1974 onwards, no new pa containers were procured, but were replaced by overseas containers.",

        ["Tragwagen_menu"] = "Carrying trolley for pa container",

		["BT10_1_name"] = "BT 10",
		["BT10_1_description"] = "Wagon for 3 pa containers converted from older wagons.",
        ["BT30_1_name"] = "BT 30",
		["BT30_1_description"] = "Wagon for 3 pa containers converted from older wagons.",
        ["BTs50_1_name"] = "BTs 50",
		["BTs50_1_description"] = "Wagon for 3 pa containers, newly built by the Bundesbahn from 1952.",
        ["BTmms51_1_name"] = "BTmms 51",
		["BTmms51_1_description"] = "Wagon for 6 pa containers, which consisted of two fixed-coupled units BTs 50.",
        ["Laabs588_1_name"] = "Laabs 588",
		["Laabs588_1_description"] = "Wagon for 6 pa containers, which consisted of two fixed-coupled wagons.",
        ["Laabkkmms588_1_name"] = "Laabkkmms 588",
		["Laabkkmms588_1_description"] = "Wagon for 6 pa containers, which consisted of two fixed-coupled wagons.",
        ["BTms55_1_name"] = "BTms 55",
		["BTms55_1_description"] = "Trolley for 4 pa containers, which was the most used.",
        ["Lbms584_1_name"] = "Lbms 584",
		["Lbms584_1_description"] = "Trolley for 4 pa containers, which was the most used.",

        ["BTmms58_name"] = "BTmms58",
        ["BTmms58_description"] = "Wagon for 5 pa containers, which was built especially for this purpose. In addition, it was possible to load the overseas containers that appeared from the end of the 1960s.",
        ["Lbs589_name"] = "Lbs 589",
        ["Lbs589_description"] = "Wagon for 5 pa containers, which was built especially for this purpose. In addition, it was possible to load the overseas containers that appeared from the end of the 1960s.",
        ["Lbms589_name"] = "Lbms 589",
        ["Lbms589_description"] = "Wagon for 5 pa containers, which was built especially for this purpose. In addition, it was possible to load the overseas containers that appeared from the end of the 1960s.",
        ["Lbms589_DBAG_name"] = "Lbms 589 (DBAG)",
        ["Lbms589_DBAG_description"] = "Wagon for 5 pa containers, which was built especially for this purpose. In addition, it was possible to load the overseas containers that appeared from the end of the 1960s.",
        ["Lbms589_DBAG_Container_name"] = "Lbms 589 (DBAG) Container",
        ["Lbms589_DBAG_Container_description"] = "Wagon built for 5 pa containers, but here it can only load overseas containers.",
    
        ["Ddihkr"] = "Ddihkr",
        ["Asset_Ddihkr"] = "Insulated pa container for liquids.",
        ["Ddihkr"] = "Ddikr",
        ["Asset_Ddikr"] = "pa container for beer.",
        ["Ddihkr"] = "Ddr",
        ["Asset_Ddr"] = "pa container for liquid gas.",
        ["Ddzkr"] = "Ddzkr",
        ["Asset_Ddzkr"] = "pa container with compressed air discharge for dust goods.",
        ["Dzkr"] = "Dzkr",
        ["Asset_Dzkr"] = "pa container with bottom discharge for cement.",
        ["Edkrt"] = "Edkrt",
        ["Asset_Edkrt"] = "pa container with fixed cover for moisture-sensitive bulk materials.",
        ["Efkr"] = "Efkr",
        ["Asset_Efkr"] = "pa container for fine dust goods.",
        ["Eikrt"] = "Eikrt",
        ["Asset_Eikrt"] = "Insulated pa container for refrigerated transports.",
        ["Ekrt"] = "Ekrt",
        ["Asset_Ekrt"] = "Closed pa container for unpacked merchant goods.",
        ["Eokrt"] = "Eokrt",
        ["Asset_Eokrt"] = "Open pa container for bulk materials that are not sensitive to weathering.",
        ["Eoskrt"] = "Eoskrt",
        ["Asset_Eoskrt"] = "Open pa container with vertical walls for bulk materials.",

	},
	de = {

		["mod_name"] = "DB Tragwagen für pa-Behälter (Mittelcontainer)",
		["mod_desc"] = "Der Einsatz von Großbehältern auf der Schiene kam nach 1945 so richtig in Fahrt. Dafür wurden spezielle Tragwagen entwickelt, die ein schnelles und einfaches Umladen ermöglichen sollten. Dieses System setzte sich in der Bundesrepublik Deutschland durch und wurde unter dem griffigen Markennamen \"Von Haus zu Haus\" bekannt. Seinen Höhepunkt erreichte der Behälterverkehr in den sechziger Jahren mit rund 25.000 Einheiten und etwa 5.700 Großbehälter-Tragwagen zu deren Beförderung. Unterwegs waren sie teilweise in einem eigens eingerichteten Städte-Schnellverkehr. Ab 1974 wurden keine neuen pa-Behälter mehr beschafft, sondern durch Überseecontainer abgelöst.",

        ["Tragwagen_menu"] = "Tragwagen für pa-Behälter",

		["BT10_1_name"] = "BT 10",
		["BT10_1_description"] = "Wagen für 3 pa-Behälter, der aus älteren Wagen umgebaut wurde.",
        ["BT30_1_name"] = "BT 30",
		["BT30_1_description"] = "Wagen für 3 pa-Behälter, der aus älteren Wagen umgebaut wurde.",
        ["BTs50_1_name"] = "BTs 50",
		["BTs50_1_description"] = "Wagen für 3 pa-Behälter, der bei der Bundesbahn ab 1952 neu gebaut wurde.",
        ["BTmms51_1_name"] = "BTmms 51",
		["BTmms51_1_description"] = "Wagen für 6 pa-Behälter, der aus zwei festgekuppelten Einheiten BTs 50 bestand.",
        ["Laabs588_1_name"] = "Laabs 588",
		["Laabs588_1_description"] = "Wagen für 6 pa-Behälter, der aus zwei festgekuppelten Wagen bestand.",
        ["Laabkkmms588_1_name"] = "Laabkkmms 588",
		["Laabkkmms588_1_description"] = "Wagen für 6 pa-Behälter, der aus zwei festgekuppelten Wagen bestand.",
        ["BTms55_1_name"] = "BTms 55",
		["BTms55_1_description"] = "Wagen für 4 pa-Behälter, der am meisten verwendet wurde.",
        ["Lbms584_1_name"] = "Lbms 584",
		["Lbms584_1_description"] = "Wagen für 4 pa-Behälter, der am meisten verwendet wurde.",

        ["BTmms58_name"] = "BTmms58",
        ["BTmms58_description"] = "Wagen für 5 pa-Behälter, der speziell für diesen Einsatzzweck gebaut wurde. Außerdem war es möglich die ab Ende der 60er Jahre aufkommenden Überseecontainer zu verladen.",
        ["Lbs589_name"] = "Lbs 589",
        ["Lbs589_description"] = "Wagen für 5 pa-Behälter, der speziell für diesen Einsatzzweck gebaut wurde. Außerdem war es möglich die ab Ende der 60er Jahre aufkommenden Überseecontainer zu verladen.",
        ["Lbms589_name"] = "Lbms 589",
        ["Lbms589_description"] = "Wagen für 5 pa-Behälter, der speziell für diesen Einsatzzweck gebaut wurde. Außerdem war es möglich die ab Ende der 60er Jahre aufkommenden Überseecontainer zu verladen.",
        ["Lbms589_DBAG_name"] = "Lbms 589 (DBAG)",
        ["Lbms589_DBAG_description"] = "Wagen für 5 pa-Behälter, der speziell für diesen Einsatzzweck gebaut wurde. Außerdem war es möglich die ab Ende der 60er Jahre aufkommenden Überseecontainer zu verladen.",
        ["Lbms589_DBAG_Container_name"] = "Lbms 589 (DBAG) Container",
        ["Lbms589_DBAG_Container_description"] = "Wagen gebaut für 5 pa-Behälter, der hier aber nur Überseecontainer laden kann.",

        ["Ddihkr"] = "Ddihkr",
        ["Asset_Ddihkr"] = "Isolierter pa-Behälter für Flüssigkeiten.",
        ["Ddihkr"] = "Ddikr",
        ["Asset_Ddikr"] = "pa-Behälter für Bier.",
        ["Ddihkr"] = "Ddr",
        ["Asset_Ddr"] = "pa-Behälter für Flüssiggas.",
        ["Ddzkr"] = "Ddzkr",
        ["Asset_Ddzkr"] = "pa-Behälter mit Druckluftentleerung für Staubgüter.",
        ["Dzkr"] = "Dzkr",
        ["Asset_Dzkr"] = "pa-Behälter mit Bodenentleerung für Zement.",
        ["Edkrt"] = "Edkrt",
        ["Asset_Edkrt"] = "pa-Behälter mit fester Abdeckung für nässeempfindliche Schüttgüter.",
        ["Efkr"] = "Efkr",
        ["Asset_Efkr"] = "pa-Behälter für Feinstaubgüter.",
        ["Eikrt"] = "Eikrt",
        ["Asset_Eikrt"] = "Isolierter pa-Behälter für Kühltransporte.",
        ["Ekrt"] = "Ekrt",
        ["Asset_Ekrt"] = "Geschlossener pa-Behälter für unverpackte Kaufmannsgüter.",
        ["Eokrt"] = "Eokrt",
        ["Asset_Eokrt"] = "Offener pa-Behälter für witterungsunempfindliche Schüttgüter.",
        ["Eoskrt"] = "Eoskrt",
        ["Asset_Eoskrt"] = "Offener pa-Behälter mit senkrechten Wänden für Schüttgüter.",

	},
}
end
